USE [master]
GO

/****** Object:  Database [Club]    Script Date: 08/12/2019 22:08:51 ******/
CREATE DATABASE [Club]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'club', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\club.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'club_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\club_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Club].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Club] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Club] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Club] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Club] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Club] SET ARITHABORT OFF 
GO

ALTER DATABASE [Club] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Club] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Club] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Club] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Club] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Club] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Club] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Club] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Club] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Club] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Club] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Club] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Club] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Club] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Club] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Club] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Club] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Club] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Club] SET  MULTI_USER 
GO

ALTER DATABASE [Club] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Club] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Club] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Club] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Club] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Club] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Club] SET  READ_WRITE 
GO

USE [Club]
GO

USE [Club]
GO

USE [Club]
GO
/****** Object:  Table [dbo].[Bookings]    Script Date: 08/12/2019 22:19:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Bookings](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CourtId] [int] NOT NULL,
	[MemberId] [int] NOT NULL,
	[Reservation] [datetime] NOT NULL,
 CONSTRAINT [PK__bookings__3213E83F26C80A65] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Courts]    Script Date: 08/12/2019 22:19:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Courts](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Reference] [varchar](20) NOT NULL,
	[SportId] [int] NOT NULL,
 CONSTRAINT [PK__courts__3213E83F26C80A65] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Members]    Script Date: 08/12/2019 22:19:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Members](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](255) NOT NULL,
	[Surname] [varchar](255) NOT NULL,
	[Phone] [varchar](20) NOT NULL,
	[Address] [varchar](255) NOT NULL,
 CONSTRAINT [PK__members__3213E83F26C80A65] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Sports]    Script Date: 08/12/2019 22:19:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sports](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](100) NOT NULL,
 CONSTRAINT [PK__sport__3213E83F26C80A65] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 08/12/2019 22:19:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [varchar](255) NOT NULL,
	[LastName] [varchar](255) NOT NULL,
	[Email] [varchar](80) NOT NULL,
	[PasswordHash] [varbinary](1024) NOT NULL,
	[PasswordSalt] [varbinary](1024) NOT NULL,
 CONSTRAINT [PK__users__3213E83F26C80A65] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Bookings]  WITH CHECK ADD  CONSTRAINT [FK_Courts_Bookings] FOREIGN KEY([CourtId])
REFERENCES [dbo].[Courts] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Bookings] CHECK CONSTRAINT [FK_Courts_Bookings]
GO
ALTER TABLE [dbo].[Bookings]  WITH CHECK ADD  CONSTRAINT [FK_Members_Bookings] FOREIGN KEY([MemberId])
REFERENCES [dbo].[Members] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Bookings] CHECK CONSTRAINT [FK_Members_Bookings]
GO
ALTER TABLE [dbo].[Courts]  WITH CHECK ADD  CONSTRAINT [FK_Sports_Courts] FOREIGN KEY([SportId])
REFERENCES [dbo].[Sports] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Courts] CHECK CONSTRAINT [FK_Sports_Courts]
GO



